# Generated by Django 5.0.3 on 2024-03-14 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GPSRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.TextField()),
                ('recorrido', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('latitude', models.FloatField()),
                ('longitud', models.FloatField()),
            ],
        ),
    ]
