# Generated by Django 5.0.3 on 2024-05-13 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_longitud_gpsregistry_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusStops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TSCode', models.TextField()),
                ('userCode', models.TextField()),
                ('name', models.TextField()),
                ('positionX', models.FloatField()),
                ('positionY', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceUserCode', models.TextField()),
                ('serviceTSCode', models.TextField()),
                ('serviceDirection', models.TextField()),
                ('order', models.IntegerField()),
                ('variant', models.TextField()),
            ],
        ),
    ]
