# Generated by Django 5.0.6 on 2024-06-17 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_busstops_routes'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpsregistry',
            name='sentido',
            field=models.CharField(choices=[('I', 'Ida'), ('R', 'Retorno')], default='I', max_length=1),
        ),
    ]
