# Generated by Django 5.0.6 on 2024-06-21 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20240621_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='Routes',
            old_name='stopTSCode',
            new_name='stop'
        ),
    ]
