# Generated by Django 5.0.6 on 2024-06-21 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20240621_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routes',
            name='stop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.busstops'),
        ),
    ]
