# Generated by Django 5.0.6 on 2024-07-06 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_routes_stop'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviationScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('busID', models.TextField()),
                ('serviceTSCode', models.TextField()),
                ('serviceDirection', models.CharField(choices=[('I', 'Ida'), ('R', 'Retorno')], default='I', max_length=1)),
            ],
        ),
    ]
