# Generated by Django 5.0.6 on 2024-07-10 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_deviationscore'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeviationScore',
            new_name='DeviationScores',
        ),
    ]
