# Generated by Django 5.0.6 on 2024-07-10 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_deviationscore_deviationscores'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpsregistry',
            name='deviation',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
