# Generated by Django 5.0.6 on 2024-07-14 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_gpsregistry_deviation'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpsregistry',
            name='speed',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
